### ISSUE TITLE
AttributeError: module 'img2pdf' has no attribute 'convert'

### ISSUE THREAD

**Issue by seok-hee97** [seok-hee97/img2pdf#1]
Traceback (most recent call last):
  File "/Users/jangseokhee/workspace/devops/image2pdf/img2pdf.py", line 32, in <module>
    makePDF(test_path)
  File "/Users/jangseokhee/workspace/devops/image2pdf/img2pdf.py", line 25, in makePDF
    file.write(img2pdf.convert(imgs))
               ^^^^^^^^^^^^^^^
AttributeError: module 'img2pdf' has no attribute 'convert'

**Comment by seok-hee97** [comment]
file name is problem 

img2pdf.py -> img-to-pdf.py
