### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by seok-hee97** [seok-hee97/img2pdf#2]
Traceback (most recent call last):
  File "/Users/jangseokhee/workspace/devops/image2pdf/img-to-pdf.py", line 34, in <module>
    makePDF(test_path)
  File "/Users/jangseokhee/workspace/devops/image2pdf/img-to-pdf.py", line 26, in makePDF
    f.write(img2pdf.convert(imgs))
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jangseokhee/anaconda3/lib/python3.11/site-packages/img2pdf.py", line 2360, in convert
    ) in read_images(
         ^^^^^^^^^^^^
  File "/Users/jangseokhee/anaconda3/lib/python3.11/site-packages/img2pdf.py", line 1537, in read_images
    im = BytesIO(rawdata)
         ^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

**Comment by seok-hee97** [comment]
기존의 사진들을 받아올때 그 사진들의 이름만 받아와서 사진을 못찾는거였음

사진의 파일경로를 같이 갖고와야지 img2pdf.convert
(img-to-pdf.py 스크립트랑 파일들의 경로가 같은게 아니니깐)



[before]
imgs = [i for i in os.listdir(path) if i.endswith(".png")]


[after]
imgs = [os.path.join(path, i) for i in os.listdir(path) if i.endswith(".png")]
